# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    elfin_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

elfin_arm_controller:
  ros__parameters:
    joints:
      - Joint_1
      - Joint_2
      - Joint_3
      - Joint_4
      - Joint_5
      - Joint_6
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity
    
    gains:
      joint_1:   {p: 10.0, i: 0.0, d: 1.1, i_clamp: 0.0}
      joint_2:   {p: 10.0, i: 0.0, d: 1.1, i_clamp: 0.0}
      joint_3:   {p: 10.0, i: 0.0, d: 1.1, i_clamp: 0.0}
      joint_4:   {p: 10.0, i: 0.0, d: 1.1, i_clamp: 0.0}
      joint_5:   {p: 10.0, i: 0.0, d: 1.1, i_clamp: 0.0}
      joint_6:   {p: 10.0, i: 0.0, d: 1.1, i_clamp: 0.0}
